## Ejercicios de práctica con Numpy

### Autor: Emilio Martínez Miranda


## Ejercicio 1:

Hacer una matriz de 8x8 con números enteros consecutivos empezando en 1. Llenado por   filas (1, 2, 3, 4, ... )

In [10]:
import numpy as np
import numpy.ma as ma

In [3]:
matriz = [[(i * 8 + j + 1) for j in range(8)] for i in range(8)]
matriz


[[1, 2, 3, 4, 5, 6, 7, 8],
 [9, 10, 11, 12, 13, 14, 15, 16],
 [17, 18, 19, 20, 21, 22, 23, 24],
 [25, 26, 27, 28, 29, 30, 31, 32],
 [33, 34, 35, 36, 37, 38, 39, 40],
 [41, 42, 43, 44, 45, 46, 47, 48],
 [49, 50, 51, 52, 53, 54, 55, 56],
 [57, 58, 59, 60, 61, 62, 63, 64]]

## Ejercicio 2:

1. Hacer una matriz de 8x8 números enteros consecutivos empezando en 1. Llenado por columnas.

2. Reemplazar los elementos que tengan al menos un 3 por un -99.

In [4]:
matriz = [[0 for i in range(8)] for j in range(8)]
n = 1

for j in range(8):
    for i in range(8):
        matriz[i][j] = n
        n += 1
        
matriz


[[1, 9, 17, 25, 33, 41, 49, 57],
 [2, 10, 18, 26, 34, 42, 50, 58],
 [3, 11, 19, 27, 35, 43, 51, 59],
 [4, 12, 20, 28, 36, 44, 52, 60],
 [5, 13, 21, 29, 37, 45, 53, 61],
 [6, 14, 22, 30, 38, 46, 54, 62],
 [7, 15, 23, 31, 39, 47, 55, 63],
 [8, 16, 24, 32, 40, 48, 56, 64]]

In [5]:
for i in range(8):
    for j in range(8):
        if "3" in str(matriz[i][j]):
            matriz[i][j] = -99
            
matriz

[[1, 9, 17, 25, -99, 41, 49, 57],
 [2, 10, 18, 26, -99, 42, 50, 58],
 [-99, 11, 19, 27, -99, -99, 51, 59],
 [4, 12, 20, 28, -99, 44, 52, 60],
 [5, -99, 21, 29, -99, 45, -99, 61],
 [6, 14, 22, -99, -99, 46, 54, 62],
 [7, 15, -99, -99, -99, 47, 55, -99],
 [8, 16, 24, -99, 40, 48, 56, 64]]

## Ahora utilizando Numpy y Numpy.ma (masks)


In [8]:
# Creación de la matriz 1 llenada por filas

m1 = np.arange(1, 65).reshape(8,8)
m1

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [9]:
# Creación de la matriz 2 llenada por columnas

m2 = m1.T
m2 

array([[ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64]])

In [11]:
# Creación de máscara y reemplazo de los números que tienen un 3

mask = np.mod(m2, 10) == 3
m2[mask] = -99

m2

array([[  1,   9,  17,  25, -99,  41,  49,  57],
       [  2,  10,  18,  26,  34,  42,  50,  58],
       [-99,  11,  19,  27,  35, -99,  51,  59],
       [  4,  12,  20,  28,  36,  44,  52,  60],
       [  5, -99,  21,  29,  37,  45, -99,  61],
       [  6,  14,  22,  30,  38,  46,  54,  62],
       [  7,  15, -99,  31,  39,  47,  55, -99],
       [  8,  16,  24,  32,  40,  48,  56,  64]])