## Ejercicios de práctica con Numpy

### Autor: Emilio Martínez Miranda


## Ejercicio 1:

Hacer una matriz de 8x8 con números enteros consecutivos empezando en 1. Llenado por   filas (1, 2, 3, 4, ... )

In [1]:
import numpy as np
import numpy.ma as ma

In [2]:
matriz = [[(i * 8 + j + 1) for j in range(8)] for i in range(8)]
matriz


[[1, 2, 3, 4, 5, 6, 7, 8],
 [9, 10, 11, 12, 13, 14, 15, 16],
 [17, 18, 19, 20, 21, 22, 23, 24],
 [25, 26, 27, 28, 29, 30, 31, 32],
 [33, 34, 35, 36, 37, 38, 39, 40],
 [41, 42, 43, 44, 45, 46, 47, 48],
 [49, 50, 51, 52, 53, 54, 55, 56],
 [57, 58, 59, 60, 61, 62, 63, 64]]

## Ejercicio 2:

1. Hacer una matriz de 8x8 números enteros consecutivos empezando en 1. Llenado por columnas.

2. Reemplazar los elementos que tengan al menos un 3 por un -99.

In [3]:
matriz = [[0 for i in range(8)] for j in range(8)]
n = 1

for j in range(8):
    for i in range(8):
        matriz[i][j] = n
        n += 1
        
matriz


[[1, 9, 17, 25, 33, 41, 49, 57],
 [2, 10, 18, 26, 34, 42, 50, 58],
 [3, 11, 19, 27, 35, 43, 51, 59],
 [4, 12, 20, 28, 36, 44, 52, 60],
 [5, 13, 21, 29, 37, 45, 53, 61],
 [6, 14, 22, 30, 38, 46, 54, 62],
 [7, 15, 23, 31, 39, 47, 55, 63],
 [8, 16, 24, 32, 40, 48, 56, 64]]

In [4]:
for i in range(8):
    for j in range(8):
        if "3" in str(matriz[i][j]):
            matriz[i][j] = -99
            
matriz

[[1, 9, 17, 25, -99, 41, 49, 57],
 [2, 10, 18, 26, -99, 42, 50, 58],
 [-99, 11, 19, 27, -99, -99, 51, 59],
 [4, 12, 20, 28, -99, 44, 52, 60],
 [5, -99, 21, 29, -99, 45, -99, 61],
 [6, 14, 22, -99, -99, 46, 54, 62],
 [7, 15, -99, -99, -99, 47, 55, -99],
 [8, 16, 24, -99, 40, 48, 56, 64]]

## Ahora utilizando Numpy y Numpy.ma (masks)


In [5]:
# Ejercicio 1
# Creación de la matriz 1 llenada por filas

m1 = np.arange(1, 65).reshape(8,8)
m1

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [6]:
# Ejercicio 2.1
# Creación de la matriz 2 llenada por columnas

m2 = m1.T
m2 

array([[ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64]])

In [7]:
# Ejercicio 2.2
# Creación de máscara y reemplazo de los números que tienen un 3

mask = np.mod(m2, 10) == 3
m2[mask] = -99

m2

array([[  1,   9,  17,  25, -99,  41,  49,  57],
       [  2,  10,  18,  26,  34,  42,  50,  58],
       [-99,  11,  19,  27,  35, -99,  51,  59],
       [  4,  12,  20,  28,  36,  44,  52,  60],
       [  5, -99,  21,  29,  37,  45, -99,  61],
       [  6,  14,  22,  30,  38,  46,  54,  62],
       [  7,  15, -99,  31,  39,  47,  55, -99],
       [  8,  16,  24,  32,  40,  48,  56,  64]])

## Ejercicio 3:

1. Reproducir la matriz [ [0.4 ... 0.44], [...], ..., [0.75 ... 0.79] ]

2. Unir B con el resultado del ejercicio anterior 2.2 para obtener una matriz de 8 filas y 13 columnas 

3. Agregar una línea al final con el promedio de cada columna

4. Agregar una columna al final con el valor máximo de cada fila

5. Guardar en un archivo

In [8]:
# Ejercicio 3.1

B = np.arange(0.4, 0.80, 0.01).reshape(8,5)

B

array([[0.4 , 0.41, 0.42, 0.43, 0.44],
       [0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54],
       [0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64],
       [0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74],
       [0.75, 0.76, 0.77, 0.78, 0.79]])

In [9]:
# Ejercicio 3.2

m3 = np.concatenate((m2,B), axis=1)

m3


array([[  1.  ,   9.  ,  17.  ,  25.  , -99.  ,  41.  ,  49.  ,  57.  ,
          0.4 ,   0.41,   0.42,   0.43,   0.44],
       [  2.  ,  10.  ,  18.  ,  26.  ,  34.  ,  42.  ,  50.  ,  58.  ,
          0.45,   0.46,   0.47,   0.48,   0.49],
       [-99.  ,  11.  ,  19.  ,  27.  ,  35.  , -99.  ,  51.  ,  59.  ,
          0.5 ,   0.51,   0.52,   0.53,   0.54],
       [  4.  ,  12.  ,  20.  ,  28.  ,  36.  ,  44.  ,  52.  ,  60.  ,
          0.55,   0.56,   0.57,   0.58,   0.59],
       [  5.  , -99.  ,  21.  ,  29.  ,  37.  ,  45.  , -99.  ,  61.  ,
          0.6 ,   0.61,   0.62,   0.63,   0.64],
       [  6.  ,  14.  ,  22.  ,  30.  ,  38.  ,  46.  ,  54.  ,  62.  ,
          0.65,   0.66,   0.67,   0.68,   0.69],
       [  7.  ,  15.  , -99.  ,  31.  ,  39.  ,  47.  ,  55.  , -99.  ,
          0.7 ,   0.71,   0.72,   0.73,   0.74],
       [  8.  ,  16.  ,  24.  ,  32.  ,  40.  ,  48.  ,  56.  ,  64.  ,
          0.75,   0.76,   0.77,   0.78,   0.79]])

In [10]:
# Ejercicio 3.3 

# fila con el promedio de cada columna 

column_mean = np.mean(m3, axis = 0)
column_mean

array([-8.25 , -1.5  ,  5.25 , 28.5  , 20.   , 26.75 , 33.5  , 40.25 ,
        0.575,  0.585,  0.595,  0.605,  0.615])

In [11]:
# se agrega la línea al final
m4 = np.append(m3, column_mean).reshape(9,13)
m4

array([[  1.   ,   9.   ,  17.   ,  25.   , -99.   ,  41.   ,  49.   ,
         57.   ,   0.4  ,   0.41 ,   0.42 ,   0.43 ,   0.44 ],
       [  2.   ,  10.   ,  18.   ,  26.   ,  34.   ,  42.   ,  50.   ,
         58.   ,   0.45 ,   0.46 ,   0.47 ,   0.48 ,   0.49 ],
       [-99.   ,  11.   ,  19.   ,  27.   ,  35.   , -99.   ,  51.   ,
         59.   ,   0.5  ,   0.51 ,   0.52 ,   0.53 ,   0.54 ],
       [  4.   ,  12.   ,  20.   ,  28.   ,  36.   ,  44.   ,  52.   ,
         60.   ,   0.55 ,   0.56 ,   0.57 ,   0.58 ,   0.59 ],
       [  5.   , -99.   ,  21.   ,  29.   ,  37.   ,  45.   , -99.   ,
         61.   ,   0.6  ,   0.61 ,   0.62 ,   0.63 ,   0.64 ],
       [  6.   ,  14.   ,  22.   ,  30.   ,  38.   ,  46.   ,  54.   ,
         62.   ,   0.65 ,   0.66 ,   0.67 ,   0.68 ,   0.69 ],
       [  7.   ,  15.   , -99.   ,  31.   ,  39.   ,  47.   ,  55.   ,
        -99.   ,   0.7  ,   0.71 ,   0.72 ,   0.73 ,   0.74 ],
       [  8.   ,  16.   ,  24.   ,  32.   ,  40.   ,  48.   , 

In [12]:
m4.shape

(9, 13)

In [13]:
# Ejercicio 3.4

# fila con valor máximo de cada fila
vmax = np.max(m4, axis=1)
vmax

array([57.  , 58.  , 59.  , 60.  , 61.  , 62.  , 55.  , 64.  , 40.25])

In [14]:
# se agrega como columna a la matriz

vmax.reshape(9,1)

m5 = np.insert(m4, [13], vmax.reshape(9,1), axis=1)
m5

array([[  1.   ,   9.   ,  17.   ,  25.   , -99.   ,  41.   ,  49.   ,
         57.   ,   0.4  ,   0.41 ,   0.42 ,   0.43 ,   0.44 ,  57.   ],
       [  2.   ,  10.   ,  18.   ,  26.   ,  34.   ,  42.   ,  50.   ,
         58.   ,   0.45 ,   0.46 ,   0.47 ,   0.48 ,   0.49 ,  58.   ],
       [-99.   ,  11.   ,  19.   ,  27.   ,  35.   , -99.   ,  51.   ,
         59.   ,   0.5  ,   0.51 ,   0.52 ,   0.53 ,   0.54 ,  59.   ],
       [  4.   ,  12.   ,  20.   ,  28.   ,  36.   ,  44.   ,  52.   ,
         60.   ,   0.55 ,   0.56 ,   0.57 ,   0.58 ,   0.59 ,  60.   ],
       [  5.   , -99.   ,  21.   ,  29.   ,  37.   ,  45.   , -99.   ,
         61.   ,   0.6  ,   0.61 ,   0.62 ,   0.63 ,   0.64 ,  61.   ],
       [  6.   ,  14.   ,  22.   ,  30.   ,  38.   ,  46.   ,  54.   ,
         62.   ,   0.65 ,   0.66 ,   0.67 ,   0.68 ,   0.69 ,  62.   ],
       [  7.   ,  15.   , -99.   ,  31.   ,  39.   ,  47.   ,  55.   ,
        -99.   ,   0.7  ,   0.71 ,   0.72 ,   0.73 ,   0.74 ,  55.   ],

In [19]:
# Ejercicio 3.5

# Guardar en un archivo

f = open('matriz_ejercicio3.txt', 'w')
f.write('--'*50)
f.write('\n\n Matriz resultante del ejercicio 3: \n\n')
f.write(str(m5))
f.write('\n')
f.close()